<?php
namespace App\Model\Entity;

class Organization{
    public $id = 1;
    public $name = 'Dionise';
    public $site = 'http://localhost/Dionise/';
    public $description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed varius nulla malesuada sem consequat tristique. Mauris malesuada finibus ligula, ac viverra nibh. Nam risus sapien, aliquet nec posuere ut, ultricies faucibus lorem. Vivamus sed velit condimentum, efficitur arcu eu, placerat nisi. Morbi eu quam tellus. Integer lobortis ornare orci. Nullam vel dolor est. Maecenas blandit erat nec sapien pretium, ultricies pulvinar magna egestas. Praesent consequat mi nec odio fringilla porta. Aenean rutrum dui vel consectetur vehicula. Aliquam erat volutpat.

    Suspendisse blandit fringilla commodo. Curabitur suscipit interdum nisl, ut malesuada tortor pellentesque vel. Sed felis nunc, hendrerit vel consectetur id, lacinia sit amet felis. Mauris vitae ullamcorper justo. Mauris interdum sit amet neque ut pulvinar. Phasellus iaculis pretium mi, non blandit mi convallis nec. Suspendisse potenti. Mauris ut metus et tellus dignissim iaculis sed at magna. Donec suscipit ornare dolor at vulputate. Sed vehicula lacinia turpis in bibendum.
    
    Aliquam aliquam blandit ligula, at blandit justo dignissim at. Nam euismod vehicula congue. Proin dictum nibh tortor, tincidunt gravida enim aliquam in. Pellentesque dapibus et nunc vitae suscipit. Nunc efficitur et dui eu consectetur. Fusce ut nunc ut elit ornare volutpat. Aenean gravida erat urna, at commodo lectus venenatis sit amet. Quisque ac urna in enim ullamcorper varius quis sit amet purus. Maecenas ut rhoncus odio. Ut vel velit tellus. Maecenas malesuada mollis venenatis. Duis porttitor mollis pharetra. Praesent varius commodo dui, vel elementum orci efficitur euismod.
    
    Cras ut placerat felis. Nulla commodo euismod velit. Praesent gravida feugiat orci, sit amet pretium dolor imperdiet condimentum. Maecenas luctus felis placerat eros iaculis, sed elementum urna hendrerit. Ut tincidunt dolor laoreet, pharetra lacus efficitur, faucibus lorem. Aliquam rutrum rutrum nunc, a dignissim quam molestie in. Aliquam cursus iaculis libero.
    
    Nam non aliquet ligula. Ut dignissim sagittis pretium. Nulla at turpis sit amet sem facilisis pellentesque. Sed dictum augue feugiat pretium fringilla. Nam erat arcu, suscipit a venenatis eu, aliquet quis nisl. Mauris suscipit risus a dictum tincidunt. Mauris eu diam metus. Maecenas ultricies turpis et nibh finibus viverra. Nulla et elementum lacus. Vivamus semper ac tortor vel faucibus. Integer id suscipit libero. Ut pretium leo imperdiet diam sagittis porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam molestie sapien id erat finibus dapibus. Nam vel erat dolor. Donec suscipit efficitur massa et venenatis.
    
    Aenean ut sodales ante, at porttitor lectus. Fusce ultricies velit enim. Sed vel leo euismod, auctor dui eu, rutrum leo. Maecenas vitae est ornare, dictum felis at, vulputate purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer commodo tellus a mauris convallis placerat. Maecenas massa neque, porttitor non velit ut, congue vehicula est. Curabitur ligula urna, sagittis ac consectetur a, accumsan vel mi.
    
    Fusce pulvinar ligula et eleifend suscipit. Donec vestibulum vehicula suscipit. Nam id pretium ante, porttitor imperdiet nisi. Vestibulum a placerat mi. Morbi purus magna, fringilla sed mauris quis, maximus vulputate metus. Phasellus odio est, venenatis quis ullamcorper condimentum, rhoncus at lacus. Vivamus vel scelerisque dui. Proin ullamcorper sodales nisl sed mattis. Curabitur commodo hendrerit urna vitae scelerisque. Proin scelerisque, enim non convallis interdum, urna nisl tempus odio, id malesuada magna nulla eget est. Curabitur laoreet magna eget justo feugiat aliquam a vitae enim. Nulla varius congue tellus non molestie. Praesent hendrerit dolor nec sem gravida volutpat. Ut sed erat sit amet est congue tincidunt. Curabitur porta a justo vel semper.
    
    Aenean vulputate, ligula quis laoreet congue, orci metus dignissim orci, cursus consectetur urna nibh id tortor. Etiam rutrum mauris ex, eget commodo tortor suscipit non. Donec aliquam dapibus metus. Nunc quis sagittis sapien. Vestibulum vel magna porttitor, vulputate mi a, fermentum risus. Aliquam fringilla vitae libero eget hendrerit. In orci mi, convallis congue dolor non, gravida consectetur odio. Vestibulum mattis tincidunt sapien vitae tincidunt. Suspendisse nunc ex, mollis ut mauris vitae, faucibus tincidunt lectus. Suspendisse eros arcu, pulvinar ut finibus vitae, auctor id urna. In fermentum dapibus ante, ut dignissim dolor finibus vel. Duis laoreet mauris id urna venenatis cursus. Aliquam efficitur, magna dignissim faucibus tincidunt, dolor elit faucibus ipsum, sit amet fringilla nisl urna eget ligula. Cras nibh diam, rhoncus sit amet velit at, pharetra dignissim nunc.
    
    Proin tempus neque sit amet nulla ornare lobortis. Vestibulum hendrerit molestie erat in accumsan. Vivamus semper justo molestie urna dignissim, eu hendrerit magna feugiat. Ut dictum arcu a ex pharetra sodales. Donec semper, augue ut blandit scelerisque, elit nunc ultricies felis, venenatis sodales ante ligula vitae lacus. Suspendisse potenti. In hac habitasse platea dictumst. In hac habitasse platea dictumst. Morbi orci libero, posuere in felis nec, aliquam laoreet magna. Curabitur eleifend arcu vel congue pellentesque. Donec non sollicitudin tortor, mollis placerat dolor. Mauris quis libero quis orci laoreet placerat.
    
    Cras ut urna nec odio euismod semper. Aliquam erat volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi ornare at mauris id cursus. Proin non massa sit amet diam malesuada gravida. Morbi dictum ante mauris, eu hendrerit dui accumsan sed. Vivamus quis tincidunt neque. Vivamus mauris arcu, pellentesque eu magna vel, sodales fringilla sem. Suspendisse efficitur enim eget fermentum ultrices. Integer non nibh gravida augue aliquet maximus vel sit amet erat. Donec consequat mattis imperdiet. Donec eget lorem egestas tortor blandit accumsan quis et lectus. Ut non erat dolor. Integer sem ligula, euismod venenatis vehicula ac, lacinia sit amet lectus.
    
    Nunc vulputate neque vel tempus molestie. Mauris urna quam, dictum pretium mi id, bibendum condimentum risus. Nulla hendrerit risus sed ultricies tristique. Donec id sollicitudin mi, vel feugiat arcu. Donec consequat eleifend porttitor. Aliquam aliquet odio non blandit bibendum. Donec luctus ligula in velit tristique, sit amet tincidunt neque viverra. Etiam aliquam lectus lectus, sit amet luctus sem ultrices nec. In hac habitasse platea dictumst. Aenean a quam scelerisque, ullamcorper mi vel, dignissim diam. Proin mollis lobortis augue, vel efficitur neque. Nullam venenatis, urna vel aliquam cursus, neque libero auctor nisi, et ultrices sem eros sed sem. Vivamus malesuada ipsum posuere, maximus justo eu, tristique leo. Aenean viverra condimentum tortor, eget congue lectus pharetra ut.
    
    Donec hendrerit augue ac magna tempor rhoncus. Aliquam eget scelerisque sem. Aliquam cursus ante vel consectetur molestie. Aliquam tincidunt dolor odio, in scelerisque elit egestas ac. Morbi eleifend ultrices erat, a dictum mauris lobortis et. Nunc non purus eget ipsum tristique hendrerit quis nec lectus. Cras venenatis cursus erat quis ultrices. Aenean cursus facilisis erat consequat imperdiet. Vivamus quis iaculis sem, vel ornare justo. Aenean venenatis vehicula leo, ac pulvinar nibh dictum et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse efficitur quam mi. In hac habitasse platea dictumst. Maecenas vel massa ut quam efficitur congue. Aenean sit amet consectetur ex.';
}